version: '3.2'
services:
  inventory:
    container_name: inventory
    image: 'palleri/inventory'
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      host: db
      user: root
      password: rootpw
      name: inventory
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0ZDk0YWNhM2YwOTk0ODdiYWU5NzkzMGI4ZmE0Nzc5OSIsImlhdCI6MTcwNjEwODk0NSwiZXhwIjoyMDIxNDY4OTQ1fQ.G4buyHo20AkyEuZnZpDixESGBekoMH0_rOBGl3G5ssk
      hahost: 10.0.20.10:8123
    volumes:
      - ./data:/var/www/


  # Database
  db:
    #    platform: linux/x86_64
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      #      MYSQL_DATABASE: inventory
      MYSQL_PASSWORD: inventorypw
      MYSQL_USER: palleri
      #      MYSQL_TCP_PORT: 3306

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      #      MYSQL_USER: palleri
      #      MYSQL_PASSWORD: inventorypw
      #      MYSQL_ROOT_PASSWORD: rootpw
